spring:
  application:
    name: smart-delivery

  profiles:
    active: local

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

info:
  app:
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: never