spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_delivery
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    default-schema: public
    schemas:
      - public

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger
    url: /openapi/openapi.yaml

server:
  port: 8080
  servlet:
    context-path: /smart-delivery

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Smart Delivery
    description: Plataforma para gerenciamento de entregas.
    version: "@project.version@"